# Generated by Django 2.0.3 on 2019-06-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('robot_id', models.IntegerField(unique=True)),
                ('task_name', models.CharField(max_length=255)),
                ('issued_time', models.DateTimeField(auto_now_add=True)),
                ('scheduled_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('Scheduled', 'SCHEDULED'), ('Active', 'ACTIVE'), ('Completed', 'COMPLETED'), ('Preempted', 'PREEMPTED'), ('Rejected', 'REJECTED')], default='Scheduled', max_length=15)),
            ],
        ),
    ]
